In [5]:
import numpy as np

# Creating Arrays
arr = np.array([1, 2, 3]) 
#Create an array from a list or tuple.
zeros_arr = np.zeros(3)
## Creates a 1D array of length 3 filled with zeros
ones_arr = np.ones((2, 3))
# Creates a 2D array of shape (2, 3) filled with ones
range_arr = np.arange(0, 10, 2)
#Create an array with regularly spaced values.
arr
zeros_arr
ones_arr
range_arr

array([0, 2, 4, 6, 8])

In [8]:
#numpy.reshape(): Reshape an array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Reshapes to a 2D array of shape (2, 3)
arr
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#numpy.transpose(): Transpose of an array.
arr = np.array([[1, 2], [3, 4]])
transposed_arr = np.transpose(arr)  # Transposes the array
transposed_arr

array([[1, 3],
       [2, 4]])

In [10]:
#numpy.concatenate(): Concatenate arrays along a given axis.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))  # Concatenates the arrays
concatenated_arr

array([1, 2, 3, 4, 5, 6])

In [11]:
import numpy as np

# Create two arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along rows (axis 0)
concatenated_rows = np.concatenate((arr1, arr2), axis=0)

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated along rows (axis 0):\n", concatenated_rows)

# Concatenate along column (axis 1)
concatenated_rows1 = np.concatenate((arr1, arr2), axis=1)
print("Concatenated along column (axis 1):\n", concatenated_rows1)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Concatenated along rows (axis 0):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated along column (axis 1):
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [20]:
# Mathematical Functions
total_sum = np.sum(arr)
mean_val = np.mean(arr)
total_sum
mean_val

2.5

In [21]:
#numpy.dot(): Compute the dot product of two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(arr1, arr2)  # Computes dot product of arr1 and arr2
dot_product

array([[19, 22],
       [43, 50]])

In [22]:
#numpy.linalg.inv(): Compute the (multiplicative) inverse of a matrix.
matrix = np.array([[4, 7], [2, 6]])
inv_matrix = np.linalg.inv(matrix)  # Computes the inverse of the matrix
inv_matrix

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [12]:
a = np.array([(1,2,3),(4,5,6)])
print(a[0,2])#print 3
print(a[0:,2])# print 3 6 


3
[3 6]


In [14]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a[0:2,2:])

[[3]
 [6]]


In [17]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(np.sqrt(a))
print(np.std(a))


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
2.581988897471611


In [18]:
a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
